#include "use_opencv.h"

#define GROUND_POINT_0_X 120
#define GROUND_POINT_0_Y 130

#define GROUND_POINT_1_X 550
#define GROUND_POINT_1_Y 130

#define GROUND_POINT_2_X 550
#define GROUND_POINT_2_Y 440

#define GROUND_POINT_3_X 120
#define GROUND_POINT_3_Y 440

#define GROUND_POINT_HEIGHT abs(GROUND_POINT_0_Y - GROUND_POINT_3_Y)
#define GROUND_POINT_WIDTH abs(GROUND_POINT_0_X - GROUND_POINT_1_X)